name: eyra-rank
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - joblib
  - pip
  - pip:
    - numpy=1.26.0
    - pandas
    - scikit-learn
    - xgboost==2.0.3    
    - polars
    - pyarrow
    - torch
    - torchvision
    - pytorch_frame
    - torchaudio
    - tqdm
    - torch_frame
    - jupyterlab
    - ipykernel
    - umap-learn
