name: eyra-rank
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - joblib
  - pip
  - pip:
    - numpy==1.26.0
    - pandas
    - scikit-learn
    - torch==2.3.0
    - pytorch_frame==0.2.2

