name: eyra-rank
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - joblib
  - pip
  - pip:
    - numpy==1.26.0
    - pandas
    - scikit-learn
    - polars
    - pyarrow
    - torch
    - pytorch_frame
    - tqdm
    - torch_frame
