name: eyra-rank
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - pip
  - pip:
    - joblib
    - numpy
    - pandas
    - scikit-learn
    - xgboost==2.0.3    
    - polars
    - pyarrow
    - torch
    - torchvision
    - torchaudio
    - tqdm

