name: eyra-rank
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - pip
  - pip:
    - joblib
    - numpy
    - pandas
    - scikit-learn
    - sentence-transformers
    - xgboost==2.0.3